// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2-ZSnxGhMSbpxR9lWipQ-JX4s8Fz3j8Q',
    appId: '1:7076696675:web:ff0f1965ca544627ab1e56',
    messagingSenderId: '7076696675',
    projectId: 'librarymanagement-80741',
    authDomain: 'librarymanagement-80741.firebaseapp.com',
    storageBucket: 'librarymanagement-80741.firebasestorage.app',
    measurementId: 'G-LSEJWDED1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNgKpj1llMLZHTIl64I5BkawDwdLRKeUg',
    appId: '1:7076696675:android:b7980bc332f24261ab1e56',
    messagingSenderId: '7076696675',
    projectId: 'librarymanagement-80741',
    storageBucket: 'librarymanagement-80741.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyCZgy34LbpFABbva1MeYEwqZPLvsJG3o',
    appId: '1:7076696675:ios:a9968c11fae92697ab1e56',
    messagingSenderId: '7076696675',
    projectId: 'librarymanagement-80741',
    storageBucket: 'librarymanagement-80741.firebasestorage.app',
    androidClientId: '7076696675-kk09pgftprvlng1ea8eaktp5ivint9lj.apps.googleusercontent.com',
    iosClientId: '7076696675-0no8ld964co4vcqen741lvc90nndloek.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyCZgy34LbpFABbva1MeYEwqZPLvsJG3o',
    appId: '1:7076696675:ios:a9968c11fae92697ab1e56',
    messagingSenderId: '7076696675',
    projectId: 'librarymanagement-80741',
    storageBucket: 'librarymanagement-80741.firebasestorage.app',
    androidClientId: '7076696675-kk09pgftprvlng1ea8eaktp5ivint9lj.apps.googleusercontent.com',
    iosClientId: '7076696675-0no8ld964co4vcqen741lvc90nndloek.apps.googleusercontent.com',
    iosBundleId: 'com.example.libraryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2-ZSnxGhMSbpxR9lWipQ-JX4s8Fz3j8Q',
    appId: '1:7076696675:web:e9713e8c8b22b655ab1e56',
    messagingSenderId: '7076696675',
    projectId: 'librarymanagement-80741',
    authDomain: 'librarymanagement-80741.firebaseapp.com',
    storageBucket: 'librarymanagement-80741.firebasestorage.app',
    measurementId: 'G-7BN20ECGWX',
  );
}
